
# BEGINNING = "FORE!!!"
# OUT  = 34
basedir = "/Users/hal/code"
basedirs = [
    "~/code",
    "~/Google Drive/colab"
]

ignored_paths = [
    "~/code/python",
    "~/code/swift"
]
# [[ignored_paths]]
# path = "~/code/python"
# [[ignored_paths]]
# path = "~/code/swift"

[[ignored_repos]]
path = "~/code/swift"
tags = []
[[ignored_repos]]
path = "~/code/python"
tags = []

[[default_tags]]
name = "functional programming"
[[default_tags]]
name = "machine learning"

[path_shortcuts]
haskell = "~/code/haskell"
swift = "~/code/swift"
ml = "~/code/ml"

[[actions]]
# PathAction = [
PathAction = [
    "~/code",
    "list code",
    "ls",
    [
        "ls -la"
    ]
]
