
# BEGINNING = "FORE!!!"
# OUT  = 34
basedir = "/Users/hal/code"
basedirs = [
    "~/code",
    "~/Google Drive/colab"
]

ignored_paths = [
    "~/code/python",
    "~/code/swift"
]
# [[ignored_paths]]
# path = "~/code/python"
# [[ignored_paths]]
# path = "~/code/swift"

[[ignored_repos]]
path = "~/code/swift"
tags = []
[[ignored_repos]]
path = "~/code/python"
tags = []

[[default_tags]]
name = "functional programming"
[[default_tags]]
name = "machine learning"

[path_shortcuts]
haskell = "~/code/haskell"
swift = "~/code/swift"
ml = "~/code/ml"

# [[actions]]
# [actions.Extra]
# path = "~/code"
# Extra = {path = "~/code"}

[[actions]]
[actions.PathAction]
path = "~/code"
[actions.PathAction.cmd]
name = "list code"
command = "ls"
args = [ "ls -la" ]

[[actions]]
[actions.NonPathAction]
[actions.NonPathAction.cmd]
name = "Where are you?"
command = "/usr/local/bin/zsh"
args = [ "ping google.com" ]

[[actions]]
[actions.NeedsAPathAction]
[actions.NeedsAPathAction.cmd]
name = "Where am I?"
command = "/usr/local/bin/zsh"
args = [ "pwd" ]
