[package]

name = "git-global"
version = "0.1.1"
authors = ["Eric Petersen <eric@ericpetersen.io>"]
description = "Keep track of all your git repositories."

homepage = "https://github.com/peap/git-global"
repository = "https://github.com/peap/git-global"
documentation = "https://docs.rs/git-global"

license = "MIT"
readme = "README.md"

keywords = ["git"]
categories = ["command-line-utilities", "development-tools"]
build = "build.rs"

[[bin]]
name = "git-global-hal"
doc = false
path = "src/main.rs"

[lib]
[dependencies]
app_dirs = "1.2.1"
clap = "2.32.0"
chrono = "0.4.6"
colored = "1.6.1"
itertools = "0.7.8"
json = "0.11.13"
lazy_static = "1.2.0"
mut_static = "5.0.0"
tui = "0.3.0"
termion = "1.5.1"
walkdir = "2.2.6"
github-gql-rs = "0.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
strfmt = "0.1.6"
pipeline = "0.5.0"
rustfix = "0.4.2"
dirs = "1.0.4"
pretty_env_logger = "0.2.5"
log = "0.4.6"
take_mut = "0.2.2"
icecream = "0.1.0"
config = "0.9.1"


[dependencies.cursive]
version = "0.9.2"
default-features = false
features = ["termion-backend"]

[dependencies.git2]
version = "0.7.5"
default-features = false  # don't want SSH/HTTPS/Curl

[dev-dependencies]
tempdir = "0.3.7"

[build-dependencies]
clap = "2.32.0"
# json = "0.11"
