[package]

name = "git-global"
version = "0.1.1"
authors = ["Eric Petersen <eric@ericpetersen.io>"]
description = "Keep track of all your git repositories."

homepage = "https://github.com/peap/git-global"
repository = "https://github.com/peap/git-global"
documentation = "https://docs.rs/git-global"

license = "MIT"
readme = "README.md"

keywords = ["git"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "git-global"
doc = false

[dependencies]
app_dirs = "1.2.1"
clap = "2"
chrono = "0.3"
colored = "1.6.0"
itertools = "0.7.3"
json = "0.11"
walkdir = "2.1.4"

[dev-dependencies]
tempdir = "0.3"

[dependencies.git2]
version = "0.6"
default-features = false  # don't want SSH/HTTPS/Curl
