[package]

name = "git-global"
version = "0.1.1"
authors = ["Eric Petersen <eric@ericpetersen.io>"]
description = "Keep track of all your git repositories."

homepage = "https://github.com/peap/git-global"
repository = "https://github.com/peap/git-global"
documentation = "https://docs.rs/git-global"

license = "MIT"
readme = "README.md"

keywords = ["git"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "git-global-hal"
doc = false
path = "src/main.rs"

[lib]
[dependencies]
app_dirs = "1.2.1"
clap = "2"
chrono = "0.3"
colored = "1.6.0"
cursive = "0.8.2"
itertools = "0.7.3"
json = "0.11"
lazy_static = "1.0.1"
mut_static = "5.0.0"
tui = "0.2.1"
termion = "1.5.1"
walkdir = "2.1.4"
github-gql-rs = "0.0.1"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.17"
strfmt = "0.1.6"

[dev-dependencies]
tempdir = "0.3"

[dependencies.git2]
version = "0.6"
default-features = false  # don't want SSH/HTTPS/Curl
