[package]

name = "git-global"
version = "0.1.1"
authors = ["Eric Petersen <eric@ericpetersen.io>"]
description = "Keep track of all your git repositories."
edition = "2018"

homepage = "https://github.com/peap/git-global"
repository = "https://github.com/peap/git-global"
documentation = "https://docs.rs/git-global"

license = "MIT"
readme = "README.md"

keywords = ["git"]
categories = ["command-line-utilities", "development-tools"]
build = "build.rs"

[[bin]]
name = "git-global-hal"
doc = false
path = "src/main.rs"

[lib]
[dependencies]
app_dirs = "1.2.1"
clap = "2.33.0"
chrono = "0.4.10"
colored = "1.9.0"
crossbeam-channel = "0.3.9"
futures = "0.3.1"
itertools = "0.8.2"
json = "0.12.0"
lazy_static = "1.4.0"
mut_static = "5.0.0"
tui = "0.7.0"
termion = "1.5.4"
walkdir = "2.2.9"
jwalk = "0.4.0"
github-rs = "0.7.0"
ring_queue = "0.2.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
strfmt = "0.1.6"
subprocess = "0.1.18"
pipeline = "0.5.0"
rustfix = "0.4.6"
dirs = "2.0.2"
pretty_env_logger = "0.3.1"
log = "0.4.8"
take_mut = "0.2.2"
icecream = "0.1.0"
config = "0.9.3"
anyhow = "1.0.25"
thiserror = "1.0.6"
tokio = { version = "0.2.2", features = ["full"] }


[dependencies.cursive]
version = "0.13.0"
default-features = false
features = ["termion-backend"]

[dependencies.git2]
version = "0.10.2"
default-features = false  # don't want SSH/HTTPS/Curl

[dev-dependencies]
tempdir = "0.3.7"

[build-dependencies]
clap = "2.33.0"
# json = "0.11"
