[env]
APP_NAME = "git-global-hal"

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install-bin]
description = "install git-global-hal globally"
workspace = false
command = "cargo"
args = ["install", "--force", "--path", "."]


[tasks.build-shell-completions]
description = "Output zsh completion info via `clap` and store it in /usr/local/share/zsh/site-functions"
script = [
	"${APP_NAME} --zsh > /usr/local/share/zsh/site-functions/_${APP_NAME}"
]
