[tasks.build-git-global-hal]
command = "cargo"
args = ["build"]

[tasks.install-git-global-hal]
description = "install git-global-hal globally"
workspace = false
command = "cargo"
args = ["install", "--force", "--bin", "git-global-hal"]


[tasks.build-shell-completions]
description = "Output zsh completion info via `clap` and store it in /usr/local/share/zsh/site-functions"
command = "git-global-hal"
args = ["--zsh", ">", "/usr/local/share/zsh/site-functions/_git-global-hal"]
