//! Subcommand implementations.
pub mod add_tags;
pub mod bullshit;
pub mod clean;
pub mod filter;
pub mod info;
pub mod list;
pub mod list_tags;
pub mod prompt;
pub mod prompt_cursive;
pub mod scan;
pub mod status;
pub mod tag;
pub mod tag_projects_redo;
pub mod utilities;
