//! Subcommand implementations.
pub mod actions;
pub mod add_tags;
pub mod clean;
pub mod filter;
pub mod github;
pub mod info;
pub mod list;
pub mod list_tags;
pub mod new_status;
pub mod prompt_cursive;
pub mod prompt_tui;
pub mod scan;
pub mod sync_status;
pub mod tag_projects;
pub mod utilities;
